name: Deploy to OpenShift

on:
  push:
    branches:
      - dev  # Altere para a branch desejada

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello"

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ""  # Adicione a URL do ambiente, se necessário
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to OpenShift
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}  # Adicione o segredo do token no GitHub
        run: |
          echo "${OPENSHIFT_TOKEN}" | oc login api.ocp-dev.bancobai.ao:6443 --username santo.andre --token - --insecure-skip-tls-verify

      - name: Run Scripts for Dev
        run: echo "Deploying to development environment"

  deploy-qua:
    runs-on: ubuntu-latest
    environment:
      name: qua
      url: ""  # Adicione a URL do ambiente, se necessário
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to OpenShift
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}  # Adicione o segredo do token no GitHub
        run: |
          echo "${OPENSHIFT_TOKEN}" | oc login api.ocp-dev.bancobai.ao:6443 --username santo.andre --token - --insecure-skip-tls-verify

      - name: Run Scripts for QA
        run: echo "Deploying to QA environment"

  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: ""  # Adicione a URL do ambiente, se necessário
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to OpenShift
        env:
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}  # Adicione o segredo do token no GitHub
        run: |
          echo "${OPENSHIFT_TOKEN}" | oc login api.ocp-dev.bancobai.ao:6443 --username santo.andre --token - --insecure-skip-tls-verify

      - name: Run Scripts for Prod
        run: echo "Deploying to production environment"
